name: "Testing"
on:
  pull_request:
  push:
      branches: [ "main" ]

env:
  NIXPKGS_ALLOW_INSECURE: "1"
  NIXPKGS_ALLOW_UNFREE: "1"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Add Nix to path if already installed"
        run: |
          if [ -d "/nix/var/nix/profiles/default/bin" ]; then
            echo "/nix/var/nix/profiles/default/bin" > "$GITHUB_PATH"
          fi
      - uses: cachix/install-nix-action@v27

      - name: "Build nix-shell derivation"
        run: nix-build shell.nix

  tests:
    runs-on: ubuntu-latest
    needs: build
    steps:      
      - uses: actions/checkout@v3

      - name: "Add Nix to path if already installed"
        run: |
          if [ -d "/nix/var/nix/profiles/default/bin" ]; then
            echo "/nix/var/nix/profiles/default/bin" > "$GITHUB_PATH"
          fi
      - uses: cachix/install-nix-action@v27
      - name: "Run test suite"
        run: |
          cd tests
          bash run_tests.sh
